version: 2

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: cd bunkernet && npm install && npm run build
      - persist_to_workspace:
          root: bunkernet
          paths: [build]

  publish:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: bunkernet/build
      - add_ssh_keys:
          fingerprints:
            - "4f:4f:31:6c:1a:6c:f3:0c:4b:3c:5e:44:15:01:56:32"
      - run: |
          npm install -g --silent gh-pages@2.0.1
          git config user.email "ci-build@bunkernet.dev"
          git config user.name "ci-build"
      - run: |
          gh-pages --dotfiles --message "[skip ci] Updates" --dist bunkernet/build

workflows:
  version: 2
  
  release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
                - master
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
