version: 2

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: cd bunkernet && ls -al
      - run: npm install
      - run: npm build
  publish:
    docker:
      - image: node
    steps:
      - checkout
      - run: docker build -t zoharcochavi/bunkernet:latest

workflows:
  version: 2
  
  release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
