version: 2

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: cd bunkernet && npm install && npm run build
  publish:
    machine: true
    steps:
      - checkout
      - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      # build the application image
      - run: docker build -t zoharcochavi/bunkernet:latest .

      # deploy the image
      - run: docker push zoharcochavi/bunkernet:latest

workflows:
  version: 2
  
  release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
                - master
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
