version: 2

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: cd bunkernet && npm install && npm run build
  publish:
    docker:
      - image: docker
    steps:
      - checkout
      - run: docker build -t zoharcochavi/bunkernet:latest

workflows:
  version: 2
  
  release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
