version: 2

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: cd bunkernet && npm install && npm run build
      - persist_to_workspace:
          root: bunkernet
          paths: [build]

  publish:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: bunkernet/build
      - add_ssh_keys:
          fingerprints:
            - "86:2e:e1:57:2c:e6:c4:ba:06:ea:87:4d:2b:6b:58:e6"
      - run: |
          npm install -g --silent gh-pages@2.0.1
          git config user.email "ci-build@bunkernet.dev"
          git config user.name "ci-build"
      - run: |
          gh-pages --dist bunkernet/build

workflows:
  version: 2
  
  release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
                - master
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
